### ISSUE TITLE
Theme.AppCompat Error!

### ISSUE THREAD

**Issue by YuganshT79** [yarolegovich/LovelyDialog#34]
When running the App I am getting this error! 
`java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:354)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                           at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
                                                                           at android.support.v7.app.AlertController.installContent(AlertController.java:226)
                                                                           at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:260)
                                                                           at android.app.Dialog.dispatchOnCreate(Dialog.java:402)
                                                                           at android.app.Dialog.show(Dialog.java:301)
                                                                           at com.yarolegovich.lovelydialog.AbsLovelyDialog.show(AbsLovelyDialog.java:163)
                                                                           at ytstudios.wall.bucket.MainActivity$checkForAppUpdates.onPostExecute(MainActivity.java:333)
                                                                           at ytstudios.wall.bucket.MainActivity$checkForAppUpdates.onPostExecute(MainActivity.java:286)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:673)
                                                                           at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:690)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)`

How should I fix this ?

**Comment by yarolegovich** [comment]
Specify a correct parent for the theme you are using:
```xml
<style name="CustomTheme" parent="Theme.AppCompat.Light.Dialog.Alert"/>
```

**Comment by YuganshT79** [comment]
Thank you !

**Comment by bellalzohir** [comment]
where we add this 
is for the style of the whole app or just for the dialog ??

**Comment by lucazin** [comment]
WholeApp
